@startuml
title test
ChangeCartridge <|-- ColorDeta
ChangeCartridge <|-- PenDeta

class PenDeta{
    pen
    limit

    setPen()
    getLimit()
}

class ColorDeta{
    colornum

    setColor()
    getColor()
}

class ChangeCartridge{

}

class Filereader{
    fileread
}

@enduml